const ActionsTypes = {
    SET_LOCATION_COUNTRY:'SET_LOCTION_COUNTRY',
    SET_LOCATION_STATE:'SET_LOCATION_STATE',
    SET_OPTION:"SET_OPTIONS",
    SET_LOGIN:"SET_USER_LOGIN",
    SET_USER:"SET_USER",
    SET_LOGOUT:"SET_USER_LOGIN_OUT",
    SET_COMPANY_ACCESS:"SET_COMPANY_ACCESS",
}
export default ActionsTypes;